[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NEXT_PUBLIC_APP_URL = "https://mapranx.com"
  NODE_VERSION = "18"
# Force deploy Sat, Aug 30, 2025 10:48:21 PM
